---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: melo
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: melo-webapp
          image: nginx
          ports:
            - containerPort: 80
        - name: webmelo
          image: saimohan3604/melo_webapp_nginx
          ports:
            - containerPort: 80

---

---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: web
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80


